<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('name' => 'Afghanistan', 'country_code' => 'AFG'),
            array('name' => 'Albania', 'country_code' => 'ALB'),
            array('name' => 'Algeria', 'country_code' => 'DZA'),
            array('name' => 'American Samoa', 'country_code' => 'ASM'),
            array('name' => 'Andorra', 'country_code' => 'AND'),
            array('name' => 'Angola', 'country_code' => 'AGO'),
            array('name' => 'Anguilla', 'country_code' => 'AIA'),
            array('name' => 'Antarctica', 'country_code' => 'ATA'),
            array('name' => 'Antigua and Barbuda', 'country_code' => 'ATG'),
            array('name' => 'Argentina', 'country_code' => 'ARG'),
            array('name' => 'Armenia', 'country_code' => 'ARM'),
            array('name' => 'Aruba', 'country_code' => 'ABW'),
            array('name' => 'Australia', 'country_code' => 'AUS'),
            array('name' => 'Austria', 'country_code' => 'AUT'),
            array('name' => 'Azerbaijan', 'country_code' => 'AZE'),
            array('name' => 'Bahamas (the)', 'country_code' => 'BHS'),
            array('name' => 'Bahrain', 'country_code' => 'BHR'),
            array('name' => 'Bangladesh', 'country_code' => 'BGD'),
            array('name' => 'Barbados', 'country_code' => 'BRB'),
            array('name' => 'Belarus', 'country_code' => 'BLR'),
            array('name' => 'Belgium', 'country_code' => 'BEL'),
            array('name' => 'Belize', 'country_code' => 'BLZ'),
            array('name' => 'Benin', 'country_code' => 'BEN'),
            array('name' => 'Bermuda', 'country_code' => 'BMU'),
            array('name' => 'Bhutan', 'country_code' => 'BTN'),
            array('name' => 'Bolivia (Plurinational State of)', 'country_code' => 'BOL'),
            array('name' => 'Bonaire, Sint Eustatius and Saba', 'country_code' => 'BES'),
            array('name' => 'Bosnia and Herzegovina', 'country_code' => 'BIH'),
            array('name' => 'Botswana', 'country_code' => 'BWA'),
            array('name' => 'Bouvet Island', 'country_code' => 'BVT'),
            array('name' => 'Brazil', 'country_code' => 'BRA'),
            array('name' => 'British Indian Ocean Territory (the)', 'country_code' => 'IOT'),
            array('name' => 'Brunei Darussalam', 'country_code' => 'BRN'),
            array('name' => 'Bulgaria', 'country_code' => 'BGR'),
            array('name' => 'Burkina Faso', 'country_code' => 'BFA'),
            array('name' => 'Burundi', 'country_code' => 'BDI'),
            array('name' => 'Cabo Verde', 'country_code' => 'CPV'),
            array('name' => 'Cambodia', 'country_code' => 'KHM'),
            array('name' => 'Cameroon', 'country_code' => 'CMR'),
            array('name' => 'Canada', 'country_code' => 'CAN'),
            array('name' => 'Cayman Islands (the)', 'country_code' => 'CYM'),
            array('name' => 'Central African Republic (the)', 'country_code' => 'CAF'),
            array('name' => 'Chad', 'country_code' => 'TCD'),
            array('name' => 'Chile', 'country_code' => 'CHL'),
            array('name' => 'China', 'country_code' => 'CHN'),
            array('name' => 'Christmas Island', 'country_code' => 'CXR'),
            array('name' => 'Cocos (Keeling) Islands (the)', 'country_code' => 'CCK'),
            array('name' => 'Colombia', 'country_code' => 'COL'),
            array('name' => 'Comoros (the)', 'country_code' => 'COM'),
            array('name' => 'Congo (the Democratic Republic of the)', 'country_code' => 'COD'),
            array('name' => 'Congo (the)', 'country_code' => 'COG'),
            array('name' => 'Cook Islands (the)', 'country_code' => 'COK'),
            array('name' => 'Costa Rica', 'country_code' => 'CRI'),
            array('name' => 'Croatia', 'country_code' => 'HRV'),
            array('name' => 'Cuba', 'country_code' => 'CUB'),
            array('name' => 'Curaçao', 'country_code' => 'CUW'),
            array('name' => 'Cyprus', 'country_code' => 'CYP'),
            array('name' => 'Czechia', 'country_code' => 'CZE'),
            array('name' => 'Côte d\'Ivoire', 'country_code' => 'CIV'),
            array('name' => 'Denmark', 'country_code' => 'DNK'),
            array('name' => 'Djibouti', 'country_code' => 'DJI'),
            array('name' => 'Dominica', 'country_code' => 'DMA'),
            array('name' => 'Dominican Republic (the)', 'country_code' => 'DOM'),
            array('name' => 'Ecuador', 'country_code' => 'ECU'),
            array('name' => 'Egypt', 'country_code' => 'EGY'),
            array('name' => 'El Salvador', 'country_code' => 'SLV'),
            array('name' => 'Equatorial Guinea', 'country_code' => 'GNQ'),
            array('name' => 'Eritrea', 'country_code' => 'ERI'),
            array('name' => 'Estonia', 'country_code' => 'EST'),
            array('name' => 'Eswatini', 'country_code' => 'SWZ'),
            array('name' => 'Ethiopia', 'country_code' => 'ETH'),
            array('name' => 'Falkland Islands (the) [Malvinas]', 'country_code' => 'FLK'),
            array('name' => 'Faroe Islands (the)', 'country_code' => 'FRO'),
            array('name' => 'Fiji', 'country_code' => 'FJI'),
            array('name' => 'Finland', 'country_code' => 'FIN'),
            array('name' => 'France', 'country_code' => 'FRA'),
            array('name' => 'French Guiana', 'country_code' => 'GUF'),
            array('name' => 'French Polynesia', 'country_code' => 'PYF'),
            array('name' => 'French Southern Territories (the)', 'country_code' => 'ATF'),
            array('name' => 'Gabon', 'country_code' => 'GAB'),
            array('name' => 'Gambia (the)', 'country_code' => 'GMB'),
            array('name' => 'Georgia', 'country_code' => 'GEO'),
            array('name' => 'Germany', 'country_code' => 'DEU'),
            array('name' => 'Ghana', 'country_code' => 'GHA'),
            array('name' => 'Gibraltar', 'country_code' => 'GIB'),
            array('name' => 'Greece', 'country_code' => 'GRC'),
            array('name' => 'Greenland', 'country_code' => 'GRL'),
            array('name' => 'Grenada', 'country_code' => 'GRD'),
            array('name' => 'Guadeloupe', 'country_code' => 'GLP'),
            array('name' => 'Guam', 'country_code' => 'GUM'),
            array('name' => 'Guatemala', 'country_code' => 'GTM'),
            array('name' => 'Guernsey', 'country_code' => 'GGY'),
            array('name' => 'Guinea', 'country_code' => 'GIN'),
            array('name' => 'Guinea-Bissau', 'country_code' => 'GNB'),
            array('name' => 'Guyana', 'country_code' => 'GUY'),
            array('name' => 'Haiti', 'country_code' => 'HTI'),
            array('name' => 'Heard Island and McDonald Islands', 'country_code' => 'HMD'),
            array('name' => 'Holy See (the)', 'country_code' => 'VAT'),
            array('name' => 'Honduras', 'country_code' => 'HND'),
            array('name' => 'Hong Kong', 'country_code' => 'HKG'),
            array('name' => 'Hungary', 'country_code' => 'HUN'),
            array('name' => 'Iceland', 'country_code' => 'ISL'),
            array('name' => 'India', 'country_code' => 'IND'),
            array('name' => 'Indonesia', 'country_code' => 'IDN'),
            array('name' => 'Iran (Islamic Republic of)', 'country_code' => 'IRN'),
            array('name' => 'Iraq', 'country_code' => 'IRQ'),
            array('name' => 'Ireland', 'country_code' => 'IRL'),
            array('name' => 'Isle of Man', 'country_code' => 'IMN'),
            array('name' => 'Israel', 'country_code' => 'ISR'),
            array('name' => 'Italy', 'country_code' => 'ITA'),
            array('name' => 'Jamaica', 'country_code' => 'JAM'),
            array('name' => 'Japan', 'country_code' => 'JPN'),
            array('name' => 'Jersey', 'country_code' => 'JEY'),
            array('name' => 'Jordan', 'country_code' => 'JOR'),
            array('name' => 'Kazakhstan', 'country_code' => 'KAZ'),
            array('name' => 'Kenya', 'country_code' => 'KEN'),
            array('name' => 'Kiribati', 'country_code' => 'KIR'),
            array('name' => 'Korea (the Democratic People\'s Republic of)', 'country_code' => 'PRK'),
            array('name' => 'Korea (the Republic of)', 'country_code' => 'KOR'),
            array('name' => 'Kuwait', 'country_code' => 'KWT'),
            array('name' => 'Kyrgyzstan', 'country_code' => 'KGZ'),
            array('name' => 'Lao People\'s Democratic Republic (the)', 'country_code' => 'LAO'),
            array('name' => 'Latvia', 'country_code' => 'LVA'),
            array('name' => 'Lebanon', 'country_code' => 'LBN'),
            array('name' => 'Lesotho', 'country_code' => 'LSO'),
            array('name' => 'Liberia', 'country_code' => 'LBR'),
            array('name' => 'Libya', 'country_code' => 'LBY'),
            array('name' => 'Liechtenstein', 'country_code' => 'LIE'),
            array('name' => 'Lithuania', 'country_code' => 'LTU'),
            array('name' => 'Luxembourg', 'country_code' => 'LUX'),
            array('name' => 'Macao', 'country_code' => 'MAC'),
            array('name' => 'Madagascar', 'country_code' => 'MDG'),
            array('name' => 'Malawi', 'country_code' => 'MWI'),
            array('name' => 'Malaysia', 'country_code' => 'MYS'),
            array('name' => 'Maldives', 'country_code' => 'MDV'),
            array('name' => 'Mali', 'country_code' => 'MLI'),
            array('name' => 'Malta', 'country_code' => 'MLT'),
            array('name' => 'Marshall Islands (the)', 'country_code' => 'MHL'),
            array('name' => 'Martinique', 'country_code' => 'MTQ'),
            array('name' => 'Mauritania', 'country_code' => 'MRT'),
            array('name' => 'Mauritius', 'country_code' => 'MUS'),
            array('name' => 'Mayotte', 'country_code' => 'MYT'),
            array('name' => 'Mexico', 'country_code' => 'MEX'),
            array('name' => 'Micronesia (Federated States of)', 'country_code' => 'FSM'),
            array('name' => 'Moldova (the Republic of)', 'country_code' => 'MDA'),
            array('name' => 'Monaco', 'country_code' => 'MCO'),
            array('name' => 'Mongolia', 'country_code' => 'MNG'),
            array('name' => 'Montenegro', 'country_code' => 'MNE'),
            array('name' => 'Montserrat', 'country_code' => 'MSR'),
            array('name' => 'Morocco', 'country_code' => 'MAR'),
            array('name' => 'Mozambique', 'country_code' => 'MOZ'),
            array('name' => 'Myanmar', 'country_code' => 'MMR'),
            array('name' => 'Namibia', 'country_code' => 'NAM'),
            array('name' => 'Nauru', 'country_code' => 'NRU'),
            array('name' => 'Nepal', 'country_code' => 'NPL'),
            array('name' => 'Netherlands (the)', 'country_code' => 'NLD'),
            array('name' => 'New Caledonia', 'country_code' => 'NCL'),
            array('name' => 'New Zealand', 'country_code' => 'NZL'),
            array('name' => 'Nicaragua', 'country_code' => 'NIC'),
            array('name' => 'Niger (the)', 'country_code' => 'NER'),
            array('name' => 'Nigeria', 'country_code' => 'NGA'),
            array('name' => 'Niue', 'country_code' => 'NIU'),
            array('name' => 'Norfolk Island', 'country_code' => 'NFK'),
            array('name' => 'Northern Mariana Islands (the)', 'country_code' => 'MNP'),
            array('name' => 'Norway', 'country_code' => 'NOR'),
            array('name' => 'Oman', 'country_code' => 'OMN'),
            array('name' => 'Pakistan', 'country_code' => 'PAK'),
            array('name' => 'Palau', 'country_code' => 'PLW'),
            array('name' => 'Palestine, State of', 'country_code' => 'PSE'),
            array('name' => 'Panama', 'country_code' => 'PAN'),
            array('name' => 'Papua New Guinea', 'country_code' => 'PNG'),
            array('name' => 'Paraguay', 'country_code' => 'PRY'),
            array('name' => 'Peru', 'country_code' => 'PER'),
            array('name' => 'Philippines (the)', 'country_code' => 'PHL'),
            array('name' => 'Pitcairn', 'country_code' => 'PCN'),
            array('name' => 'Poland', 'country_code' => 'POL'),
            array('name' => 'Portugal', 'country_code' => 'PRT'),
            array('name' => 'Puerto Rico', 'country_code' => 'PRI'),
            array('name' => 'Qatar', 'country_code' => 'QAT'),
            array('name' => 'Republic of North Macedonia', 'country_code' => 'MKD'),
            array('name' => 'Romania', 'country_code' => 'ROU'),
            array('name' => 'Russian Federation (the)', 'country_code' => 'RUS'),
            array('name' => 'Rwanda', 'country_code' => 'RWA'),
            array('name' => 'Réunion', 'country_code' => 'REU'),
            array('name' => 'Saint Barthélemy', 'country_code' => 'BLM'),
            array('name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_code' => 'SHN'),
            array('name' => 'Saint Kitts and Nevis', 'country_code' => 'KNA'),
            array('name' => 'Saint Lucia', 'country_code' => 'LCA'),
            array('name' => 'Saint Martin (French part)', 'country_code' => 'MAF'),
            array('name' => 'Saint Pierre and Miquelon', 'country_code' => 'SPM'),
            array('name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VCT'),
            array('name' => 'Samoa', 'country_code' => 'WSM'),
            array('name' => 'San Marino', 'country_code' => 'SMR'),
            array('name' => 'Sao Tome and Principe', 'country_code' => 'STP'),
            array('name' => 'Saudi Arabia', 'country_code' => 'SAU'),
            array('name' => 'Senegal', 'country_code' => 'SEN'),
            array('name' => 'Serbia', 'country_code' => 'SRB'),
            array('name' => 'Seychelles', 'country_code' => 'SYC'),
            array('name' => 'Sierra Leone', 'country_code' => 'SLE'),
            array('name' => 'Singapore', 'country_code' => 'SGP'),
            array('name' => 'Sint Maarten (Dutch part)', 'country_code' => 'SXM'),
            array('name' => 'Slovakia', 'country_code' => 'SVK'),
            array('name' => 'Slovenia', 'country_code' => 'SVN'),
            array('name' => 'Solomon Islands', 'country_code' => 'SLB'),
            array('name' => 'Somalia', 'country_code' => 'SOM'),
            array('name' => 'South Africa', 'country_code' => 'ZAF'),
            array('name' => 'South Georgia and the South Sandwich Islands', 'country_code' => 'SGS'),
            array('name' => 'South Sudan', 'country_code' => 'SSD'),
            array('name' => 'Spain', 'country_code' => 'ESP'),
            array('name' => 'Sri Lanka', 'country_code' => 'LKA'),
            array('name' => 'Sudan (the)', 'country_code' => 'SDN'),
            array('name' => 'Suriname', 'country_code' => 'SUR'),
            array('name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJM'),
            array('name' => 'Sweden', 'country_code' => 'SWE'),
            array('name' => 'Switzerland', 'country_code' => 'CHE'),
            array('name' => 'Syrian Arab Republic', 'country_code' => 'SYR'),
            array('name' => 'Taiwan (Province of China)', 'country_code' => 'TWN'),
            array('name' => 'Tajikistan', 'country_code' => 'TJK'),
            array('name' => 'Tanzania, United Republic of', 'country_code' => 'TZA'),
            array('name' => 'Thailand', 'country_code' => 'THA'),
            array('name' => 'Timor-Leste', 'country_code' => 'TLS'),
            array('name' => 'Togo', 'country_code' => 'TGO'),
            array('name' => 'Tokelau', 'country_code' => 'TKL'),
            array('name' => 'Tonga', 'country_code' => 'TON'),
            array('name' => 'Trinidad and Tobago', 'country_code' => 'TTO'),
            array('name' => 'Tunisia', 'country_code' => 'TUN'),
            array('name' => 'Turkey', 'country_code' => 'TUR'),
            array('name' => 'Turkmenistan', 'country_code' => 'TKM'),
            array('name' => 'Turks and Caicos Islands (the)', 'country_code' => 'TCA'),
            array('name' => 'Tuvalu', 'country_code' => 'TUV'),
            array('name' => 'Uganda', 'country_code' => 'UGA'),
            array('name' => 'Ukraine', 'country_code' => 'UKR'),
            array('name' => 'United Arab Emirates (the)', 'country_code' => 'ARE'),
            array('name' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'country_code' => 'GBR'),
            array('name' => 'United States Minor Outlying Islands (the)', 'country_code' => 'UMI'),
            array('name' => 'United States of America (the)', 'country_code' => 'USA'),
            array('name' => 'Uruguay', 'country_code' => 'URY'),
            array('name' => 'Uzbekistan', 'country_code' => 'UZB'),
            array('name' => 'Vanuatu', 'country_code' => 'VUT'),
            array('name' => 'Venezuela (Bolivarian Republic of)', 'country_code' => 'VEN'),
            array('name' => 'Viet Nam', 'country_code' => 'VNM'),
            array('name' => 'Virgin Islands (British)', 'country_code' => 'VGB'),
            array('name' => 'Virgin Islands (U.S.)', 'country_code' => 'VIR'),
            array('name' => 'Wallis and Futuna', 'country_code' => 'WLF'),
            array('name' => 'Western Sahara', 'country_code' => 'ESH'),
            array('name' => 'Yemen', 'country_code' => 'YEM'),
            array('name' => 'Zambia', 'country_code' => 'ZMB'),
            array('name' => 'Zimbabwe', 'country_code' => 'ZWE'),
            array('name' => 'Åland Islands', 'country_code' => 'ALA')
        );
        DB::table("countries")->insert($countries);
    }
}